export const LOAD_LIST = 'LOAD_LIST'
export const LOAD_PAGE_LIST = 'LOAD_PAGE_LIST'
export const LOADING_LIST = 'START_LOAD_LIST'
export const ERROR_LIST = 'ERROR_LIST'
export const ERROR_ITEM = 'ERROR_ITEM'
export const LOAD_LIST_ITEM = 'LOAD_LIST_ITEM'
export const LOAD_PAGE_NEXT_PREV = 'LOAD_PAGE_NEXT_PREV'
export const LOAD_LIST_SEARCH = 'LOAD_LIST_SEARCH'

export const SOCKET_CONNECT = 'SOCKET_CONNECT'
export const SOCKET_DISCONNECT = 'SOCKET_DISCONNECT'
export const SOCKET_RECONNECT = 'SOCKET_RECONNECT'
export const SOCKET_ERROR = 'SOCKET_ERROR'
export const SOCKET_MSG = 'SOCKET_MSG'




